### ISSUE TITLE
Application Runner

### ISSUE THREAD

**Issue by om26er** [xconnio/xconn-ruby#11]
Application runner is a CLI tool that will allow us to run WAMP components. The tool will be able to read a yaml config which will contain details on how to connect to a router (config design may change)

```yaml
version: 1
transports:
  - type: websocket
    url: ws://localhost:8080/ws

authenticators:
  - type: cryptosign
    realm: realmX
    authid: john
    private-key: 53d551d8f6c9e5aec4554c7d7c617202fad7c8b1e288ad3fec4f66017bdd4900
```
